apiVersion: apps/v1
kind: Deployment
metadata:
  name: nng-trade-simulator-deployment
  labels:
    app: nng-trade-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nng-trade-simulator
  template:
    metadata:
      labels:
        app: nng-trade-simulator
    spec:
      containers:
        - name: nng-trade-simulator
          image: nordicsapplicationregistry.azurecr.io/nng-abbo-trade-simulator-azure:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 1024Mi

